### ISSUE TITLE
Support NATS Streaming

### ISSUE THREAD

**Issue by stepanstipl** [pires/nats-operator#6]
At first let me say that this is super cool, love the concept of operators & thanks for doing this with NATS.

I was was wondering (and would like to see) if there are any plans to support NATS Streaming?

**Comment by pires** [comment]
Yes, as soon as NATS Streaming supports clustering.

**Comment by stepanstipl** [comment]
Ahh I didn't realise it doesn't yet, my bad, thanks :) - https://github.com/nats-io/nats-streaming-server/issues/13

**Comment by pires** [comment]
There is no such thing as of today and it seems very far away, even at the discussion level.

**Comment by jsenon** [comment]
Clustering is now supported by ants since v0.8. Any plan to add streaming to existing operator?

**Comment by pires** [comment]
This issue is deprecated in favor of the more recent https://github.com/nats-io/nats-operator/issues/18.
