### ISSUE TITLE
TPR name unclear

### ISSUE THREAD

**Issue by pst** [pires/nats-operator#7]
I'm very excited about this operator and giving it a try. In https://github.com/pires/nats-operator/blob/master/pkg/controller/controller.go#L38 the TPR name is set to `management.nats.io` which also seems to be the TPR that's created when I run the operator.

The example however defines the kind as `NatsCluster` https://github.com/pires/nats-operator/blob/master/example/example-nats-cluster.yaml

However there is no `natscluster` TRP.

What am I missing?

**Comment by pires** [comment]
Possibly some mess up when merging. Unfortunately, I haven't had the time to move forward with this implementation but would be great to have someone else helping out as well.

**Comment by pst** [comment]
I'm working on a site that's basically a curated [catalog of operators](https://www.kubestack.com/). I've also written the Memcached operator there and am working on the one for MongoDB (very early). My Go isn't very strong though, my own operators are in Python. I won't be much help due to my limited Go and the fact that I don't know anything about NATS.

I will give this TPR name issue a try though. That should be easy enough to fix. I would assume you agree that `NatsCluster` is the better name?

**Comment by pires** [comment]
> I would assume you agree that NatsCluster is the better name.

Correct. `management.nats.io` is or should be the API group, while `NatsCluster` is the API object.

I paused this work because of some TPR bugs. Need to check if they've been fixed or not.
